# Generated by Django 3.2.6 on 2021-08-24 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_question_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='body',
            new_name='text',
        ),
    ]
