# Generated by Django 3.2.6 on 2021-08-30 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0004_rename_body_answer_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='slug',
            field=models.SlugField(default='hi', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
